
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: